# Generated by Django 4.1.9 on 2023-06-02 14:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('oauth_id', models.UUIDField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('categoty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.documentcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('tahun', models.IntegerField()),
                ('file', models.FileField(upload_to='dokumen/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.documentcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.documenttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMenuRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indikator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('data', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KelompokSatuanMutu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True)),
                ('data_dukung', models.TextField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('jenis_indikator', models.IntegerField(choices=[(1, 'Kuantitatif'), (2, 'Kualitatif'), (3, 'Radio')], default=1)),
                ('bobot_nilai', models.FloatField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LembagaAkreditasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.IntegerField(choices=[(1, 'PUSAT'), (2, 'PORTAL')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_evaluasi_diri', models.DateField()),
                ('end_evaluasi_diri', models.DateField()),
                ('start_desk_evaluation', models.DateField()),
                ('end_desk_evaluation', models.DateField()),
                ('start_visitasi', models.DateField()),
                ('end_visitasi', models.DateField()),
                ('lembaga_akreditasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lembagaakreditasi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SatuanMutu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True)),
                ('data_dukung', models.TextField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('jenis_indikator', models.IntegerField(choices=[(1, 'Kuantitatif'), (2, 'Kualitatif'), (3, 'Radio')], default=1)),
                ('bobot_nilai', models.FloatField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Standar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True)),
                ('data_dukung', models.TextField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('jenis_indikator', models.IntegerField(choices=[(1, 'Kuantitatif'), (2, 'Kualitatif'), (3, 'Radio')], default=1)),
                ('bobot_nilai', models.FloatField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandarNasional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubStandar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True)),
                ('data_dukung', models.TextField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('jenis_indikator', models.IntegerField(choices=[(1, 'Kuantitatif'), (2, 'Kualitatif'), (3, 'Radio')], default=1)),
                ('bobot_nilai', models.FloatField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TahunPeriode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tahun', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=225)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitPenunjang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=5)),
                ('address', models.TextField()),
                ('desc', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Direktorat',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.unit')),
                ('code', models.CharField(max_length=5)),
                ('address', models.TextField()),
                ('desc', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('app.unit',),
        ),
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.unit')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.unit',),
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.unit')),
                ('code', models.CharField(max_length=10)),
                ('akreditas', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'Baik Sekali'), (5, 'Unggul')])),
                ('no_sk', models.CharField(max_length=255)),
                ('start_akreditasi', models.DateField()),
                ('end_akreditasi', models.DateField()),
                ('file_akrediarasi', models.FileField(upload_to='upload/')),
                ('address', models.TextField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('fakultas_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_studi_set', to='app.fakultas')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.unit',),
        ),
        migrations.CreateModel(
            name='Rektorat',
            fields=[
                ('unit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.unit')),
                ('code', models.CharField(max_length=5)),
                ('address', models.TextField()),
                ('desc', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('app.unit',),
        ),
        migrations.CreateModel(
            name='UserBackOffice',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.user',),
        ),
        migrations.CreateModel(
            name='Visitasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.indikator')),
                ('sub_standar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.substandar')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Temuan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daftar_temuan', models.TextField()),
                ('jenis_temuan', models.IntegerField(choices=[(1, 'Observasi / Minor'), {'KTS / Mayor', 2}])),
                ('akar_masalah', models.TextField()),
                ('rekomendasi', models.TextField()),
                ('peningkatan', models.TextField(blank=True)),
                ('lampiran', models.FileField(upload_to='upload/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('sub_standar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.substandar')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='substandar',
            name='jenjang',
            field=models.ManyToManyField(to='app.unit'),
        ),
        migrations.AddField(
            model_name='substandar',
            name='lembaga_akreditasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lembagaakreditasi'),
        ),
        migrations.AddField(
            model_name='substandar',
            name='plotting_unit_kerja',
            field=models.ManyToManyField(related_name='substandar_plotting_unit_kerja', to='app.unit'),
        ),
        migrations.AddField(
            model_name='substandar',
            name='standar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.standar'),
        ),
        migrations.AddField(
            model_name='substandar',
            name='tahun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tahunperiode'),
        ),
        migrations.AddField(
            model_name='substandar',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.menu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandarNasionalPeriodeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periode')),
                ('standar_nasional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.standarnasional')),
            ],
        ),
        migrations.AddField(
            model_name='standar',
            name='jenjang',
            field=models.ManyToManyField(to='app.unit'),
        ),
        migrations.AddField(
            model_name='standar',
            name='lembaga_akreditasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lembagaakreditasi'),
        ),
        migrations.AddField(
            model_name='standar',
            name='satuan_mutu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.satuanmutu'),
        ),
        migrations.AddField(
            model_name='standar',
            name='tahun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tahunperiode'),
        ),
        migrations.AddField(
            model_name='standar',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SpmiGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.CharField(max_length=255, null=True)),
                ('unit', models.IntegerField(choices=[(1, 'PUSAT'), (2, 'PORTAL')])),
                ('menus', models.ManyToManyField(through='app.GroupMenuRelation', to='app.menu')),
            ],
            options={
                'verbose_name_plural': 'SPMI Groups',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='satuanmutu',
            name='jenjang',
            field=models.ManyToManyField(to='app.unit'),
        ),
        migrations.AddField(
            model_name='satuanmutu',
            name='kelompok_satuan_mutu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kelompoksatuanmutu'),
        ),
        migrations.AddField(
            model_name='satuanmutu',
            name='lembaga_akreditasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lembagaakreditasi'),
        ),
        migrations.AddField(
            model_name='satuanmutu',
            name='tahun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tahunperiode'),
        ),
        migrations.AddField(
            model_name='satuanmutu',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RencanaTindakLanjut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rencana_aksi', models.TextField(blank=True)),
                ('penanggung_jawab', models.TextField(blank=True)),
                ('target_penyelesaian', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Belum'), (2, 'Sudah')])),
                ('lampiran', models.FileField(upload_to='upload/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('temuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.temuan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='periode',
            name='standar_nasional',
            field=models.ManyToManyField(through='app.StandarNasionalPeriodeRelation', to='app.standarnasional'),
        ),
        migrations.AddField(
            model_name='periode',
            name='tahun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tahunperiode'),
        ),
        migrations.CreateModel(
            name='NilaiMutu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nilai_mutu', models.FloatField()),
                ('desc', models.TextField()),
                ('lembaga_akreditasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lembagaakreditasi')),
                ('tahun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tahunperiode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kelompoksatuanmutu',
            name='jenjang',
            field=models.ManyToManyField(to='app.unit'),
        ),
        migrations.AddField(
            model_name='kelompoksatuanmutu',
            name='lembaga_akreditasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lembagaakreditasi'),
        ),
        migrations.AddField(
            model_name='kelompoksatuanmutu',
            name='tahun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tahunperiode'),
        ),
        migrations.AddField(
            model_name='kelompoksatuanmutu',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indikator',
            name='sub_standar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.substandar'),
        ),
        migrations.CreateModel(
            name='GroupSubMenuRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('group_menu_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.groupmenurelation')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.submenu')),
            ],
        ),
        migrations.AddField(
            model_name='groupmenurelation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.spmigroup'),
        ),
        migrations.AddField(
            model_name='groupmenurelation',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.menu'),
        ),
        migrations.AddField(
            model_name='groupmenurelation',
            name='submenus',
            field=models.ManyToManyField(through='app.GroupSubMenuRelation', to='app.submenu'),
        ),
        migrations.CreateModel(
            name='GroupCustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluasiDiri',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('dokuments', models.ManyToManyField(to='app.dokumen')),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.indikator')),
                ('sub_standar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.substandar')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app.spmigroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='UserPortal',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.user',),
        ),
        migrations.CreateModel(
            name='TargetNilaiMutu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nilai_target', models.FloatField()),
                ('desc', models.TextField()),
                ('lembaga_akreditasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lembagaakreditasi')),
                ('tahun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tahunperiode')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programstudi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dokumen',
            name='pogram_studi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.programstudi'),
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nik', models.CharField(max_length=50)),
                ('gelar_depan', models.CharField(max_length=5)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('gelar_belakang', models.CharField(max_length=30)),
                ('jenis_kelamin', models.IntegerField(choices=[(1, 'Laki-Laki'), (2, 'Perempuan')])),
                ('instansi', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programstudi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
