# Generated by Django 4.1.9 on 2023-06-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='pogram_studi',
        ),
    ]
