# Generated by Django 4.1.9 on 2023-06-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_file_akrediarasi_programstudi_file_akreditasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='temuan',
            name='jenis_temuan',
            field=models.IntegerField(choices=[(1, 'Observasi / Minor'), (2, 'KTS / Mayor')]),
        ),
    ]
