# Generated by Django 4.1.9 on 2023-06-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditor',
            name='program_studi',
        ),
        migrations.AddField(
            model_name='auditor',
            name='program_studis',
            field=models.ManyToManyField(to='app.programstudi'),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='gelar_belakang',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditor',
            name='gelar_depan',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
