# Generated by Django 4.1.9 on 2023-06-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_auditor_program_studi_auditor_program_studis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditor',
            name='program_studis',
        ),
        migrations.AddField(
            model_name='auditor',
            name='units',
            field=models.ManyToManyField(to='app.unit'),
        ),
    ]
