# Generated by Django 4.1.9 on 2023-06-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_jenis_kelamin_auditor_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttype',
            old_name='categoty',
            new_name='category_id',
        ),
        migrations.AlterField(
            model_name='auditor',
            name='units_id',
            field=models.ManyToManyField(to='app.unit'),
        ),
    ]
