# Generated by Django 4.1.9 on 2023-06-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_categoty_documenttype_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokumen',
            old_name='type',
            new_name='type_id',
        ),
        migrations.RemoveField(
            model_name='dokumen',
            name='category',
        ),
    ]
