# Generated by Django 4.1.9 on 2023-06-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_type_dokumen_type_id_remove_dokumen_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='unit',
            new_name='unit_type',
        ),
    ]
