# Generated by Django 4.1.9 on 2023-06-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_lembaga_akreditasi_periode_lembaga_akreditasi_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelompoksatuanmutu',
            old_name='jenjang',
            new_name='jenjang_id',
        ),
        migrations.RenameField(
            model_name='kelompoksatuanmutu',
            old_name='lembaga_akreditasi',
            new_name='lembaga_akreditasi_id',
        ),
        migrations.RenameField(
            model_name='satuanmutu',
            old_name='jenjang',
            new_name='jenjang_id',
        ),
        migrations.RenameField(
            model_name='satuanmutu',
            old_name='lembaga_akreditasi',
            new_name='lembaga_akreditasi_id',
        ),
        migrations.RenameField(
            model_name='satuanmutu',
            old_name='tahun',
            new_name='tahun_id',
        ),
        migrations.RenameField(
            model_name='standar',
            old_name='jenjang',
            new_name='jenjang_id',
        ),
        migrations.RenameField(
            model_name='standar',
            old_name='lembaga_akreditasi',
            new_name='lembaga_akreditasi_id',
        ),
        migrations.RenameField(
            model_name='standar',
            old_name='tahun',
            new_name='tahun_id',
        ),
        migrations.RenameField(
            model_name='substandar',
            old_name='jenjang',
            new_name='jenjang_id',
        ),
        migrations.RenameField(
            model_name='substandar',
            old_name='lembaga_akreditasi',
            new_name='lembaga_akreditasi_id',
        ),
        migrations.RenameField(
            model_name='substandar',
            old_name='tahun',
            new_name='tahun_id',
        ),
        migrations.RemoveField(
            model_name='kelompoksatuanmutu',
            name='tahun',
        ),
        migrations.AddField(
            model_name='kelompoksatuanmutu',
            name='tahun_id',
            field=models.ForeignKey(default="c54818c7-b0de-4b1d-8dc6-7fb8626db83c", on_delete=django.db.models.deletion.CASCADE, to='app.tahunperiode'),
            preserve_default=False,
        ),
    ]
