# Generated by Django 4.1.9 on 2023-06-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_sub_standar_evaluasidiri_sub_standar_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluasidiri',
            old_name='dokuments',
            new_name='dokumen_id',
        ),
        migrations.RenameField(
            model_name='evaluasidiri',
            old_name='indikator',
            new_name='indikator_id',
        ),
        migrations.RenameField(
            model_name='groupmenurelation',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='groupmenurelation',
            old_name='menu',
            new_name='menu_id',
        ),
        migrations.RenameField(
            model_name='groupsubmenurelation',
            old_name='submenu',
            new_name='submenu_id',
        ),
        migrations.RenameField(
            model_name='nilaimutu',
            old_name='lembaga_akreditasi',
            new_name='lembaga_akreditasi_id',
        ),
        migrations.RenameField(
            model_name='nilaimutu',
            old_name='tahun',
            new_name='tahun_id',
        ),
        migrations.RenameField(
            model_name='rencanatindaklanjut',
            old_name='temuan',
            new_name='temuan_id',
        ),
        migrations.RenameField(
            model_name='standarnasionalperioderelation',
            old_name='periode',
            new_name='periode_id',
        ),
        migrations.RenameField(
            model_name='standarnasionalperioderelation',
            old_name='standar_nasional',
            new_name='standar_nasional_id',
        ),
        migrations.RenameField(
            model_name='submenu',
            old_name='menu',
            new_name='menu_id',
        ),
        migrations.RenameField(
            model_name='targetnilaimutu',
            old_name='lembaga_akreditasi',
            new_name='lembaga_akreditasi_id',
        ),
        migrations.RenameField(
            model_name='targetnilaimutu',
            old_name='program_studi',
            new_name='program_studi_id',
        ),
        migrations.RenameField(
            model_name='targetnilaimutu',
            old_name='tahun',
            new_name='tahun_id',
        ),
        migrations.RenameField(
            model_name='visitasi',
            old_name='indikator',
            new_name='indikator_id',
        ),
    ]
