# Generated by Django 4.1.9 on 2023-06-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_category_id_documenttype_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditor',
            name='lembaga_akreditasi_id',
        ),
        migrations.AddField(
            model_name='auditor',
            name='lembaga_akreditasi_id',
            field=models.ManyToManyField(to='app.lembagaakreditasi'),
        ),
    ]
